                                                               │~
# agrible schema locations                                                               │~
export AS_DIR=~/PycharmProjects/agrible-schema                           │~
source ~/PycharmProjects/agrible-schema/as-docker.sh                                     │~
                                                                                         │~
# agrible mfr locations                                                                  │~
export MFR_DIR=~/PycharmProjects/morningfarmreport                       │~
export PDAPI_DIR=~/PycharmProjects/product-data-api                      │~
export PACKAGECLOUD_MASTER_TOKEN=your-token-here

